default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: postgres
  password:
  pool: 5

development:
  <<: *default
  database: photobooth_development


test:
  <<: *default
  database: photobooth_test
